# Generated by Django 6.0.2 on 2026-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coursecategory_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50, null=True)),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Call Back Request',
                'verbose_name_plural': 'Call Back Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Natya Arts, SG Arcade, KT Gopalan Rd, Kottooli, Kozhikode, Kerala 673016')),
                ('phone', models.CharField(default='+91 75598 61455', max_length=50)),
                ('whatsapp', models.CharField(default='+91 75598 61455', max_length=50)),
                ('email', models.EmailField(default='info@natyaarts.com', max_length=254)),
                ('twitter', models.URLField(blank=True, default='https://twitter.com')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Info & Settings',
                'verbose_name_plural': 'Contact Info & Settings',
            },
        ),
    ]
